[tool.poetry]
name = "gausspyplus"
version = "0.3.0"
description = "A fully automated Gaussian decomposition package for emission line spectra."
authors = ["Manuel Riener <manuel.riener@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
astropy = ">=5.3"
lmfit = ">=1.2"
matplotlib = ">=3.7"
networkx = ">=2.8"
numpy = ">=1.24"
scipy = ">=1.10"
tqdm = ">=4.62"

[tool.poetry.group.dev.dependencies]
jupyterlab = ">=4.0"
pytest = ">=8.0"
black = ">=24.0"
pre-commit = ">=3.5"

[tool.black]
line-length = 119

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
